# SPDX-License-Identifier: GPL-2.0

ifdef CONFIG_MODEL_N970F
include arch/arm64/boot/dts/N970F.mk
endif

ifdef CONFIG_MODEL_N975F
include arch/arm64/boot/dts/N975F.mk
endif

ifdef CONFIG_MODEL_N976B
include arch/arm64/boot/dts/N976B.mk
endif
